### ISSUE TITLE
Problem with table name

### ISSUE THREAD

**Issue by kiil** [edkedk99/hledger2psql#1]
> hledger2psql -f test.journal -d postgresql://admin:admin@localhost:7501/db -t data

Gives me this error:
```
Traceback (most recent call last):
  File "/home/lk/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lk/.local/bin/hledger2psql", line 8, in <module>
    sys.exit(hledger2psql())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lk/.local/lib/python3.10/site-packages/hledger2psql/cli.py", line 49, in hledger2psql
    log = save_db(df, db_url, table_name, file, start)
  File "/home/lk/.local/lib/python3.10/site-packages/hledger2psql/hledger2psql.py", line 69, in save_db
    rows_query = conn.execute(f"select count(*) from {table_name}").fetchone()
  File "/home/lk/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'select count(*) from data'
```

**Comment by edkedk99** [comment]
Bug fixed, please reinstall with the command:

```
pip uninstall hledger2psql && pip install git+https://github.com/edkedk99/hledger2psql.git
```

Please share the result

**Comment by kiil** [comment]
The bug is indeed fixed, thanks!

**Comment by edkedk99** [comment]
There was a breaking change in sqlalchemy. Great
